---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    jkube.eclipse.org/git-commit: 8f3834d0342bac49b98fcb23fccc68308510193d
    jkube.eclipse.org/git-url: https://github.com/Teja-11/jkube
    jkube.eclipse.org/git-branch: master
  labels:
    app: vertx-4
    provider: jkube
    version: 1.16.2
    group: org.eclipse.jkube.quickstarts.maven
    app.kubernetes.io/part-of: org.eclipse.jkube.quickstarts.maven
    app.kubernetes.io/managed-by: jkube
    app.kubernetes.io/name: vertx-4
    app.kubernetes.io/version: 1.16.2
  name: vertx-4
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: vertx-4
      provider: jkube
      group: org.eclipse.jkube.quickstarts.maven
      app.kubernetes.io/name: vertx-4
      app.kubernetes.io/part-of: org.eclipse.jkube.quickstarts.maven
      app.kubernetes.io/managed-by: jkube
  template:
    metadata:
      annotations:
        jkube.eclipse.org/git-commit: 8f3834d0342bac49b98fcb23fccc68308510193d
        jkube.eclipse.org/git-url: https://github.com/Teja-11/jkube
        jkube.eclipse.org/git-branch: master
      labels:
        app: vertx-4
        provider: jkube
        version: 1.16.2
        group: org.eclipse.jkube.quickstarts.maven
        app.kubernetes.io/part-of: org.eclipse.jkube.quickstarts.maven
        app.kubernetes.io/managed-by: jkube
        app.kubernetes.io/name: vertx-4
        app.kubernetes.io/version: 1.16.2
      name: vertx-4
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: maven/vertx-4:1.16.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
        name: vertx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
        securityContext:
          privileged: false
